import type {Metadata} from 'next'
import {Geist, Geist_Mono} from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import {ThemeProvider} from 'next-themes'
import React from 'react'
 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
        	bg-[#A7D7C5] text-black min-h-screen dark:bg-[#1E1E1E] dark:text-white
        `}
      >
      <ThemeProvider attribute='class' enableSystem defaultTheme='system'>
	      <Header />
	      {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
